// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG7311_ICEFinal.Data;

#nullable disable

namespace PROG7311_ICEFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            AssignedDate = new DateTime(2026, 4, 29, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8684),
                            BookingDate = new DateTime(2026, 4, 29, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8682),
                            CompletionDate = new DateTime(2026, 4, 30, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8687),
                            CustomerId = 1,
                            Description = "Computer running slow, multiple popups",
                            ServiceType = "Virus Removal",
                            Status = "Completed",
                            TechnicianId = 2
                        },
                        new
                        {
                            BookingId = 2,
                            AssignedDate = new DateTime(2026, 5, 3, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8690),
                            BookingDate = new DateTime(2026, 5, 3, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8689),
                            CustomerId = 2,
                            Description = "Laptop screen cracked",
                            ServiceType = "Hardware Repair",
                            Status = "In Progress",
                            TechnicianId = 2
                        },
                        new
                        {
                            BookingId = 3,
                            BookingDate = new DateTime(2026, 5, 5, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8691),
                            CustomerId = 3,
                            Description = "External hard drive not recognized",
                            ServiceType = "Data Recovery",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Main St, Johannesburg",
                            Email = "jarrud@gmail.com",
                            IsActive = true,
                            Name = "Jarrud Cochrane",
                            PhoneNumber = "5551112222",
                            RegisteredDate = new DateTime(2026, 3, 6, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8632)
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Oak Ave, Cape Town",
                            Email = "hermalia@gmail.com",
                            IsActive = true,
                            Name = "Hermalia Naidoo",
                            PhoneNumber = "5553334444",
                            RegisteredDate = new DateTime(2026, 4, 6, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8634)
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "789 Pine Rd, Durban",
                            Email = "denzyl@gmail.com",
                            IsActive = true,
                            Name = "Denzyl Govender",
                            PhoneNumber = "5555556666",
                            RegisteredDate = new DateTime(2026, 4, 21, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8637)
                        });
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "admin@pcsociety.com",
                            FirstName = "Devashni",
                            HireDate = new DateTime(2025, 5, 6, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8508),
                            IsActive = true,
                            LastName = "Naidoo",
                            Password = "admin123",
                            PhoneNumber = "1111111111",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "john.tech@pcsociety.com",
                            FirstName = "Jenna",
                            HireDate = new DateTime(2025, 11, 6, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8522),
                            IsActive = true,
                            LastName = "Martin",
                            Password = "tech123",
                            PhoneNumber = "2222222222",
                            Role = "Technician",
                            Username = "technician"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "sarah.sales@pcsociety.com",
                            FirstName = "Priyanka",
                            HireDate = new DateTime(2026, 2, 6, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8525),
                            IsActive = true,
                            LastName = "Govender",
                            Password = "sales123",
                            PhoneNumber = "3333333333",
                            Role = "Sales",
                            Username = "sales"
                        });
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Amount = 1500.00m,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 4, 26, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8659),
                            OrderStatus = "Received",
                            ProductName = "Gaming PC",
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 2,
                            Amount = 89.99m,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 5, 1, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8664),
                            OrderStatus = "Processing",
                            ProductName = "Laptop Repair Kit",
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 3,
                            Amount = 299.99m,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 5, 3, 8, 6, 4, 470, DateTimeKind.Local).AddTicks(8666),
                            OrderStatus = "Dispatched",
                            ProductName = "Monitor",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Booking", b =>
                {
                    b.HasOne("PROG7311_ICEFinal.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG7311_ICEFinal.Models.Employee", "Technician")
                        .WithMany("Bookings")
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Customer");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Order", b =>
                {
                    b.HasOne("PROG7311_ICEFinal.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PROG7311_ICEFinal.Models.Employee", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
